version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports: 
      - 1972
      - 52773
      - 53773
    volumes:
      - ./:/irisrun/repo
      #- ./frontend:/usr/irissys/csp/deploy